application:
  subdomain: duck-ui
  background_task: false
  multi_instance: false
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://duck-ui:5522/

services:
  duck-ui:
    # upstream: ghcr.io/caioricciuti/duck-ui:1.2.1
    image: ghcr.io/caioricciuti/duck-ui:1.2.1
    environment:
      - DUCK_UI_PORT=5522
